channels:
  - nodefaults
  - bioconda
  - conda-forge
dependencies:
  - python = 3.9
  - pip
  - abnumber == 0.3.2
  - anarci == 2020.04.23
  - hmmer >= 3.1
  - pip:
    - click >= 7
    - pandas
    - sqlalchemy < 2
    - flask
    - redis
    - celery
    - biopython
    - pytest
    - requests
    - tqdm
    - xlsxwriter
    - humanize
    - sapiens >= 1.0.4
