channels:
  - nodefaults
  - bioconda
  - conda-forge
dependencies:
  - python = 3.8
  - pip
  - abnumber == 0.3.0
  - anarci == 2020.04.23
  - hmmer >= 3.1
  - pip:
    - click >= 7
    - pandas
    - sqlalchemy
    - flask
    - redis
    - celery
    - biopython
    - pytest
    - requests
    - tqdm
    - xlsxwriter
    - humanize
    - sapiens
