channels:
  - nodefaults
  - bioconda
  - conda-forge
dependencies:
  - python = 3.9
  - pip<24.1 # due to error in omegaconf (dependency of fairseq)
  - abnumber == 0.3.2
  - anarci == 2020.04.23
  - hmmer >= 3.1
  - pip:
    - click >= 7
    - pandas < 2.2
    - sqlalchemy < 2
    - flask < 3.0.0
    - werkzeug < 3.0.0
    - redis
    - celery
    - biopython
    - pytest
    - requests
    - tqdm
    - xlsxwriter
    - humanize
    - sapiens >= 1.0.4
